version: '3.8'
services:
  auth:
    build: ./auth
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: auth-db
    depends_on:
      - db
  teacher:
    build: ./teacher
    ports:
      - 5001:5001
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: teacher-db
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8000:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgAdmin:
